"""Update create_date field

Revision ID: e4c16f9e4157
Revises: 01fb47cd4c5c
Create Date: 2025-07-10 15:10:17.295780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c16f9e4157'
down_revision = '01fb47cd4c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
